/**
 * TECS-CATALOG-VISIBILITY-POLICY-STORAGE-001 — Slice G
 * Production / QA Runtime Playwright Visibility Policy Verification
 *
 * Tests: E2E-01 through E2E-11
 * Target: https://app.texqtic.com (controlled via PLAYWRIGHT_BASE_URL env var)
 *
 * Run:
 *   npx playwright test tests/e2e/catalog-visibility-policy-gating.spec.ts
 *
 * Required env vars (set before running — never commit passwords):
 *
 *   QA_BUYER_A_ORG_ID      UUID of the org with slug 'qa-buyer-a'
 *   QA_BUYER_A_PASSWORD    Password for qa.buyer.wvg.a@texqtic.com
 *
 *   QA_BUYER_B_ORG_ID      UUID of the org with slug 'qa-buyer' (Buyer B — REQUESTED rel.)
 *   QA_BUYER_B_PASSWORD    Password for qa.buyer@texqtic.com
 *
 *   QA_BUYER_C_ORG_ID      UUID of the org with slug 'qa-buyer-c' (Buyer C — no relationship)
 *   QA_BUYER_C_PASSWORD    Password for qa.buyer.knt.c@texqtic.com
 *
 *   QA_B2B_ORG_ID          UUID of the org with slug 'qa-b2b' (supplier / item owner)
 *   QA_B2B_PASSWORD        Password for qa.b2b@texqtic.com
 *
 * Optional:
 *   PLAYWRIGHT_BASE_URL    Defaults to https://app.texqtic.com
 *
 * All tests skip automatically (BLOCKED_BY_AUTH) if any required credential is absent.
 * Tests do NOT mutate data — all assertions are read-only except E2E-06 (RFQ draft creation).
 *
 * QA data contract (seeded by Slice F — bfb3f64):
 *   QA-B2B-FAB-002  publicationPosture=B2B_PUBLIC  catalogVisibilityPolicyMode=NULL  (open)
 *   QA-B2B-FAB-003  publicationPosture=B2B_PUBLIC  priceDisclosurePolicyMode=RELATIONSHIP_ONLY
 *   QA-B2B-FAB-004  publicationPosture=B2B_PUBLIC  catalogVisibilityPolicyMode=APPROVED_BUYER_ONLY
 *   QA-B2B-FAB-005  publicationPosture=B2B_PUBLIC  catalogVisibilityPolicyMode=APPROVED_BUYER_ONLY
 *   QA-B2B-FAB-006  publicationPosture=PRIVATE_OR_AUTH_ONLY  catalogVisibilityPolicyMode=HIDDEN
 *
 *   Buyer A (qa-buyer-a) ↔ qa-b2b: APPROVED
 *   Buyer B (qa-buyer)   ↔ qa-b2b: REQUESTED
 *   Buyer C (qa-buyer-c) ↔ qa-b2b: (no relationship record)
 *
 * Predecessor commits:
 *   bfb3f64  qa(seed): restore visibility policy intent via catalog_visibility_policy_mode
 *   9c71d14  security(ai): exclude catalog_visibility_policy_mode from all AI paths
 *   59e9207  feat(rfq): add item-level visibility policy gate to RFQ prefill and submit
 *   57b6e6c  prompt-sliceC catalog: wire visibility policy resolver into catalog browse and PDP routes
 *   9d29798  migration(catalog): add catalog_visibility_policy_mode column
 *   feb9e5f  feat(catalog): add visibility policy resolver with fallback mapping
 */

// Note: @playwright/test is an npx / QA-only dependency — not a project devDependency.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error @playwright/test resolved via npx at test run time
import { test, expect } from '@playwright/test';
// @ts-expect-error @playwright/test resolved via npx at test run time
import type { APIRequestContext, APIResponse } from '@playwright/test';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

// ─── Base URL ────────────────────────────────────────────────────────────────
const BASE_URL = (process.env.PLAYWRIGHT_BASE_URL ?? 'https://app.texqtic.com').replace(/\/$/, '');

// ─── QA identity constants (emails are deterministic from seed) ──────────────
const QA_BUYER_A_EMAIL = 'qa.buyer.wvg.a@texqtic.com';
const QA_BUYER_B_EMAIL = 'qa.buyer@texqtic.com';
const QA_BUYER_C_EMAIL = 'qa.buyer.knt.c@texqtic.com';
const QA_B2B_EMAIL     = 'qa.b2b@texqtic.com';

// ─── Method A: file-based auth state (.auth/*.json — gitignored) ─────────────
// Generated by: pnpm exec tsx tests/e2e/setup-auth-state.ts
// Preferred over env vars — no passwords ever stored or passed to this process.
interface StoredAuthState { token: string; orgId: string; }

function loadStoredAuth(name: string): StoredAuthState | null {
  try {
    const file = join(process.cwd(), '.auth', `${name}.json`);
    if (!existsSync(file)) return null;
    const parsed = JSON.parse(readFileSync(file, 'utf8')) as unknown;
    const s = parsed as StoredAuthState;
    if (typeof s.token === 'string' && s.token.length > 0 &&
        typeof s.orgId === 'string' && s.orgId.length > 0) {
      return s;
    }
    return null;
  } catch { return null; }
}

const storedA = loadStoredAuth('qa-buyer-a');
const storedB = loadStoredAuth('qa-buyer-b');
const storedC = loadStoredAuth('qa-buyer-c');
const storedS = loadStoredAuth('qa-b2b');
const FILE_AUTH_AVAILABLE = storedA !== null && storedB !== null && storedC !== null && storedS !== null;

// ─── Method B: env-var credentials (fallback) ────────────────────────────────
const QA_BUYER_A_ORG_ID   = process.env.QA_BUYER_A_ORG_ID   ?? '';
const QA_BUYER_A_PASSWORD = process.env.QA_BUYER_A_PASSWORD ?? '';
const QA_BUYER_B_ORG_ID   = process.env.QA_BUYER_B_ORG_ID   ?? '';
const QA_BUYER_B_PASSWORD = process.env.QA_BUYER_B_PASSWORD ?? '';
const QA_BUYER_C_ORG_ID   = process.env.QA_BUYER_C_ORG_ID   ?? '';
const QA_BUYER_C_PASSWORD = process.env.QA_BUYER_C_PASSWORD ?? '';
const QA_B2B_ORG_ID       = process.env.QA_B2B_ORG_ID       ?? '';
const QA_B2B_PASSWORD     = process.env.QA_B2B_PASSWORD     ?? '';
const ENV_AUTH_AVAILABLE =
  QA_BUYER_A_ORG_ID.length > 0 && QA_BUYER_A_PASSWORD.length > 0 &&
  QA_BUYER_B_ORG_ID.length > 0 && QA_BUYER_B_PASSWORD.length > 0 &&
  QA_BUYER_C_ORG_ID.length > 0 && QA_BUYER_C_PASSWORD.length > 0 &&
  QA_B2B_ORG_ID.length > 0     && QA_B2B_PASSWORD.length > 0;

// ─── Auth availability (Method A preferred, Method B fallback) ───────────────
const CREDENTIALS_AVAILABLE = FILE_AUTH_AVAILABLE || ENV_AUTH_AVAILABLE;
const AUTH_METHOD: 'file' | 'env' | 'none' =
  FILE_AUTH_AVAILABLE ? 'file' : ENV_AUTH_AVAILABLE ? 'env' : 'none';

// ─── Session-scoped JWT tokens (populated in beforeAll) ───────────────────────
let tokenA = '';  // Buyer A — APPROVED relationship with qa-b2b
let tokenB = '';  // Buyer B — REQUESTED relationship with qa-b2b
let tokenC = '';  // Buyer C — no relationship with qa-b2b
let tokenS = '';  // Supplier qa-b2b — item owner

// ─── Resolved runtime IDs (populated in beforeAll) ───────────────────────────
let supplierOrgId = '';  // qa-b2b org UUID (resolved via eligible-suppliers or env var)
let fab002ItemId  = '';  // QA-B2B-FAB-002: B2B_PUBLIC, no visibility gate
let fab004ItemId  = '';  // QA-B2B-FAB-004: B2B_PUBLIC, APPROVED_BUYER_ONLY
let fab005ItemId  = '';  // QA-B2B-FAB-005: B2B_PUBLIC, APPROVED_BUYER_ONLY
let fab006ItemId  = '';  // QA-B2B-FAB-006: PRIVATE_OR_AUTH_ONLY, HIDDEN

// ─── Helper: login and return JWT ─────────────────────────────────────────────
async function loginQA(
  request: APIRequestContext,
  email: string,
  password: string,
  tenantId: string,
): Promise<string> {
  const res: APIResponse = await request.post(`${BASE_URL}/api/auth/tenant/login`, {
    headers: { 'Content-Type': 'application/json' },
    data: { email, password, tenantId },
  });
  const body = await res.json() as { success: boolean; data?: { token?: string } };
  if (!res.ok() || !body.success || typeof body.data?.token !== 'string') {
    throw new Error(
      `QA login failed for ${email}: HTTP ${res.status()} success=${body.success}`,
    );
  }
  return body.data.token;
}

// ─── Helper: auth headers ─────────────────────────────────────────────────────
function authHeaders(token: string): Record<string, string> {
  return {
    Authorization: `Bearer ${token}`,
    'Content-Type': 'application/json',
  };
}

// ─── beforeAll: authenticate all four QA identities, resolve UUIDs ───────────
test.beforeAll(async ({ request }: { request: APIRequestContext }) => {
  if (!CREDENTIALS_AVAILABLE) return;

  if (AUTH_METHOD === 'file') {
    // Method A: load pre-captured tokens from .auth/*.json — no login calls needed
    tokenA = storedA!.token;
    tokenB = storedB!.token;
    tokenC = storedC!.token;
    tokenS = storedS!.token;
    supplierOrgId = storedS!.orgId;  // qa-b2b's orgId is stored in .auth/qa-b2b.json
  } else {
    // Method B: authenticate via API using env var credentials
    [tokenA, tokenB, tokenC, tokenS] = await Promise.all([
      loginQA(request, QA_BUYER_A_EMAIL, QA_BUYER_A_PASSWORD, QA_BUYER_A_ORG_ID),
      loginQA(request, QA_BUYER_B_EMAIL, QA_BUYER_B_PASSWORD, QA_BUYER_B_ORG_ID),
      loginQA(request, QA_BUYER_C_EMAIL, QA_BUYER_C_PASSWORD, QA_BUYER_C_ORG_ID),
      loginQA(request, QA_B2B_EMAIL,     QA_B2B_PASSWORD,     QA_B2B_ORG_ID),
    ]);
    supplierOrgId = QA_B2B_ORG_ID;
  }

  // If supplierOrgId still empty (env method without QA_B2B_ORG_ID set):
  // resolve qa-b2b org UUID via GET /api/tenant/b2b/eligible-suppliers
  if (!supplierOrgId) {
    const suppliersRes: APIResponse = await request.get(
      `${BASE_URL}/api/tenant/b2b/eligible-suppliers`,
      { headers: authHeaders(tokenA) },
    );
    const suppliersBody = await suppliersRes.json() as {
      success: boolean;
      data?: Array<{ id: string; slug: string }>;
    };
    if (!suppliersRes.ok() || !suppliersBody.success) {
      throw new Error(`Failed to resolve eligible suppliers: HTTP ${suppliersRes.status()}`);
    }
    const entry = (suppliersBody.data ?? []).find((s) => s.slug === 'qa-b2b');
    if (!entry) {
      throw new Error(
        'qa-b2b supplier not found in /api/tenant/b2b/eligible-suppliers — ' +
        'check that qa-b2b has publication_posture=B2B_PUBLIC and publicEligibilityPosture=PUBLICATION_ELIGIBLE',
      );
    }
    supplierOrgId = entry.id;
  }

  // Resolve FAB-002, FAB-004, FAB-005 UUIDs from Buyer A catalog browse
  // (Buyer A is APPROVED → sees APPROVED_BUYER_ONLY items)
  const buyerABrowseRes: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
    { headers: authHeaders(tokenA) },
  );
  const buyerABrowseBody = await buyerABrowseRes.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  if (!buyerABrowseRes.ok() || !buyerABrowseBody.success) {
    throw new Error(
      `Failed to browse qa-b2b catalog as Buyer A: HTTP ${buyerABrowseRes.status()}`,
    );
  }
  const buyerAItems = buyerABrowseBody.data?.items ?? [];
  fab002ItemId = buyerAItems.find((i) => i.sku === 'QA-B2B-FAB-002')?.id ?? '';
  fab004ItemId = buyerAItems.find((i) => i.sku === 'QA-B2B-FAB-004')?.id ?? '';
  fab005ItemId = buyerAItems.find((i) => i.sku === 'QA-B2B-FAB-005')?.id ?? '';

  // Resolve FAB-006 UUID from supplier's own catalog view
  // (FAB-006 is HIDDEN and never appears in buyer browse responses)
  const supplierCatalogRes: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/items?limit=100`,
    { headers: authHeaders(tokenS) },
  );
  const supplierCatalogBody = await supplierCatalogRes.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  if (supplierCatalogRes.ok() && supplierCatalogBody.success) {
    fab006ItemId =
      (supplierCatalogBody.data?.items ?? []).find((i) => i.sku === 'QA-B2B-FAB-006')?.id ?? '';
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// E2E-01: Buyer A (APPROVED) catalog browse includes APPROVED_BUYER_ONLY items
// ─────────────────────────────────────────────────────────────────────────────
test('E2E-01: Buyer A (APPROVED) sees APPROVED_BUYER_ONLY items in catalog browse', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: QA credential env vars not set');

  const res: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
    { headers: authHeaders(tokenA) },
  );
  expect(res.ok(), `Expected 200, got HTTP ${res.status()}`).toBe(true);

  const body = await res.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  expect(body.success).toBe(true);

  const skus = (body.data?.items ?? []).map((i) => i.sku);

  // APPROVED buyer must see APPROVED_BUYER_ONLY items
  expect(skus, 'FAB-004 (APPROVED_BUYER_ONLY) must be visible to APPROVED buyer').toContain(
    'QA-B2B-FAB-004',
  );
  expect(skus, 'FAB-005 (APPROVED_BUYER_ONLY) must be visible to APPROVED buyer').toContain(
    'QA-B2B-FAB-005',
  );
  // HIDDEN item must NOT appear regardless of relationship
  expect(skus, 'FAB-006 (HIDDEN) must not appear for any buyer').not.toContain('QA-B2B-FAB-006');
});

// ─────────────────────────────────────────────────────────────────────────────
// E2E-02: Buyer B (REQUESTED) catalog browse excludes APPROVED_BUYER_ONLY items
// ─────────────────────────────────────────────────────────────────────────────
test('E2E-02: Buyer B (REQUESTED) catalog browse excludes APPROVED_BUYER_ONLY items', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: QA credential env vars not set');

  const res: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
    { headers: authHeaders(tokenB) },
  );
  expect(res.ok(), `Expected 200, got HTTP ${res.status()}`).toBe(true);

  const body = await res.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  expect(body.success).toBe(true);

  const skus = (body.data?.items ?? []).map((i) => i.sku);

  // REQUESTED buyer must NOT see APPROVED_BUYER_ONLY items
  expect(
    skus,
    'FAB-004 (APPROVED_BUYER_ONLY) must be absent for REQUESTED buyer',
  ).not.toContain('QA-B2B-FAB-004');
  expect(
    skus,
    'FAB-005 (APPROVED_BUYER_ONLY) must be absent for REQUESTED buyer',
  ).not.toContain('QA-B2B-FAB-005');
  // HIDDEN must also be absent
  expect(skus, 'FAB-006 (HIDDEN) must not appear for any buyer').not.toContain('QA-B2B-FAB-006');
});

// ─────────────────────────────────────────────────────────────────────────────
// E2E-03: Buyer C (no relationship) catalog browse excludes APPROVED_BUYER_ONLY items
// ─────────────────────────────────────────────────────────────────────────────
test('E2E-03: Buyer C (no relationship) catalog browse excludes APPROVED_BUYER_ONLY items', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: QA credential env vars not set');

  const res: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
    { headers: authHeaders(tokenC) },
  );
  expect(res.ok(), `Expected 200, got HTTP ${res.status()}`).toBe(true);

  const body = await res.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  expect(body.success).toBe(true);

  const skus = (body.data?.items ?? []).map((i) => i.sku);

  expect(
    skus,
    'FAB-004 (APPROVED_BUYER_ONLY) must be absent for buyer with no relationship',
  ).not.toContain('QA-B2B-FAB-004');
  expect(
    skus,
    'FAB-005 (APPROVED_BUYER_ONLY) must be absent for buyer with no relationship',
  ).not.toContain('QA-B2B-FAB-005');
  expect(skus, 'FAB-006 (HIDDEN) must not appear for any buyer').not.toContain('QA-B2B-FAB-006');
});

// ─────────────────────────────────────────────────────────────────────────────
// E2E-04: Direct PDP access to HIDDEN item returns 404 for APPROVED buyer
// ─────────────────────────────────────────────────────────────────────────────
test('E2E-04: Direct PDP access to HIDDEN item (FAB-006) returns 404 for APPROVED buyer', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: QA credential env vars not set');
  test.skip(
    !fab006ItemId,
    'BLOCKED: FAB-006 item UUID not resolved — verify QA_B2B_PASSWORD is set and QA-B2B-FAB-006 exists',
  );

  const res: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/items/${fab006ItemId}`,
    { headers: authHeaders(tokenA) },
  );
  // HIDDEN item PDP must return 404 (non-disclosing) for any buyer, including APPROVED
  expect(
    res.status(),
    'HIDDEN item PDP must return 404 for APPROVED buyer (non-disclosing gate)',
  ).toBe(404);
});

// ─────────────────────────────────────────────────────────────────────────────
// E2E-05: Direct PDP access to HIDDEN item returns 404 for no-relationship buyer
// ─────────────────────────────────────────────────────────────────────────────
test('E2E-05: Direct PDP access to HIDDEN item (FAB-006) returns 404 for no-relationship buyer', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: QA credential env vars not set');
  test.skip(
    !fab006ItemId,
    'BLOCKED: FAB-006 item UUID not resolved — verify QA_B2B_PASSWORD is set and QA-B2B-FAB-006 exists',
  );

  const res: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/items/${fab006ItemId}`,
    { headers: authHeaders(tokenC) },
  );
  expect(
    res.status(),
    'HIDDEN item PDP must return 404 for no-relationship buyer',
  ).toBe(404);
});

// ─────────────────────────────────────────────────────────────────────────────
// E2E-06: Buyer A (APPROVED) can successfully initiate RFQ draft from PUBLIC item
// ─────────────────────────────────────────────────────────────────────────────
test('E2E-06: Buyer A (APPROVED) can prefill RFQ draft from B2B_PUBLIC item (FAB-002)', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: QA credential env vars not set');
  test.skip(
    !fab002ItemId,
    'BLOCKED: FAB-002 item UUID not resolved — item may be missing from qa-b2b catalog',
  );

  const res: APIResponse = await request.post(
    `${BASE_URL}/api/tenant/rfqs/drafts/from-catalog-item`,
    {
      headers: authHeaders(tokenA),
      data: { catalogItemId: fab002ItemId, selectedQuantity: 100 },
    },
  );
  // Route returns 201 on successful draft creation
  expect(res.status(), `Expected 201, got HTTP ${res.status()}`).toBe(201);

  const body = await res.json() as {
    success: boolean;
    data?: { draft?: { id: string; status: string } };
  };
  expect(body.success).toBe(true);
  // RFQ draft created: data.draft.id must be present and status must be INITIATED
  expect(body.data?.draft?.id, 'Expected draft id in response').toBeTruthy();
  expect(body.data?.draft?.status, 'Expected draft status INITIATED').toBe('INITIATED');
});

// ─────────────────────────────────────────────────────────────────────────────
// E2E-07: [Data-unblocked by Slice F — bfb3f64]
// APPROVED_BUYER_ONLY item (FAB-004) is absent from no-relationship buyer browse
// ─────────────────────────────────────────────────────────────────────────────
test(
  'E2E-07 [Slice F unblocked]: FAB-004 (APPROVED_BUYER_ONLY) absent from no-relationship buyer browse',
  async ({ request }: { request: APIRequestContext }) => {
    test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: QA credential env vars not set');

    const res: APIResponse = await request.get(
      `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
      { headers: authHeaders(tokenC) },
    );
    expect(res.ok(), `Expected 200, got HTTP ${res.status()}`).toBe(true);

    const body = await res.json() as {
      success: boolean;
      data?: { items: Array<{ id: string; sku: string | null }> };
    };
    expect(body.success).toBe(true);

    const skus = (body.data?.items ?? []).map((i) => i.sku);

    // Slice F set catalogVisibilityPolicyMode=APPROVED_BUYER_ONLY on FAB-004 and FAB-005.
    // A buyer with no relationship must not see these items.
    expect(
      skus,
      'FAB-004 (APPROVED_BUYER_ONLY) must be absent from no-relationship buyer browse [E2E-07]',
    ).not.toContain('QA-B2B-FAB-004');
    expect(
      skus,
      'FAB-005 (APPROVED_BUYER_ONLY) must be absent from no-relationship buyer browse [E2E-07]',
    ).not.toContain('QA-B2B-FAB-005');
  },
);

// ─────────────────────────────────────────────────────────────────────────────
// E2E-08: [Data-unblocked by Slice F — bfb3f64]
// HIDDEN item (FAB-006) absent from ALL buyer browse responses
// ─────────────────────────────────────────────────────────────────────────────
test(
  'E2E-08 [Slice F unblocked]: FAB-006 (HIDDEN) absent from all buyer browse responses',
  async ({ request }: { request: APIRequestContext }) => {
    test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: QA credential env vars not set');

    // Browse as all three buyers simultaneously
    const [resA, resB, resC]: APIResponse[] = await Promise.all([
      request.get(
        `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
        { headers: authHeaders(tokenA) },
      ),
      request.get(
        `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
        { headers: authHeaders(tokenB) },
      ),
      request.get(
        `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
        { headers: authHeaders(tokenC) },
      ),
    ]);

    const buyerLabels = [
      ['Buyer A (APPROVED)', resA],
      ['Buyer B (REQUESTED)', resB],
      ['Buyer C (no relationship)', resC],
    ] as [string, APIResponse][];

    for (const [label, res] of buyerLabels) {
      expect(res.ok(), `${label} browse request failed: HTTP ${res.status()}`).toBe(true);
      const body = await res.json() as {
        success: boolean;
        data?: { items: Array<{ sku: string | null }> };
      };
      const skus = (body.data?.items ?? []).map((i) => i.sku);
      expect(
        skus,
        `FAB-006 (HIDDEN) must not appear in ${label} browse response [E2E-08]`,
      ).not.toContain('QA-B2B-FAB-006');
    }
  },
);

// ─────────────────────────────────────────────────────────────────────────────
// E2E-09: [Data-unblocked by Slice F — bfb3f64]
// APPROVED_BUYER_ONLY item blocks RFQ prefill for non-approved buyer
// ─────────────────────────────────────────────────────────────────────────────
test(
  'E2E-09 [Slice F unblocked]: FAB-004 (APPROVED_BUYER_ONLY) blocks RFQ prefill for REQUESTED buyer',
  async ({ request }: { request: APIRequestContext }) => {
    test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: QA credential env vars not set');
    test.skip(
      !fab004ItemId,
      'BLOCKED: FAB-004 UUID not resolved — regression in Buyer A catalog browse (item not returned)',
    );

    const res: APIResponse = await request.post(
      `${BASE_URL}/api/tenant/rfqs/drafts/from-catalog-item`,
      {
        headers: authHeaders(tokenB),
        data: { catalogItemId: fab004ItemId, selectedQuantity: 100 },
      },
    );
    expect(res.ok(), `Expected 200 envelope, got HTTP ${res.status()}`).toBe(true);

    const body = await res.json() as {
      success: boolean;
      data?: { ok: boolean; reason?: string };
    };
    expect(body.success).toBe(true);

    // Visibility gate: RFQ prefill for APPROVED_BUYER_ONLY item with REQUESTED buyer
    // returns ok: false with a visibility-gate reason
    expect(
      body.data?.ok,
      `RFQ prefill must be denied for REQUESTED buyer on APPROVED_BUYER_ONLY item [E2E-09]`,
    ).toBe(false);
    expect(
      ['ITEM_NOT_AVAILABLE', 'ELIGIBILITY_REQUIRED'],
      `Visibility gate reason must be ITEM_NOT_AVAILABLE or ELIGIBILITY_REQUIRED, got: ${body.data?.reason}`,
    ).toContain(body.data?.reason);
  },
);

// ─────────────────────────────────────────────────────────────────────────────
// E2E-10: Anti-leakage — no visibility policy fields in buyer catalog API response
// ─────────────────────────────────────────────────────────────────────────────
test('E2E-10: Buyer catalog browse response does not leak catalogVisibilityPolicyMode or publicationPosture', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: QA credential env vars not set');

  // Use Buyer A (APPROVED) to get the most items — maximises field coverage
  const res: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
    { headers: authHeaders(tokenA) },
  );
  expect(res.ok(), `Expected 200, got HTTP ${res.status()}`).toBe(true);

  const body = await res.json() as {
    success: boolean;
    data?: { items: Array<Record<string, unknown>> };
  };
  expect(body.success).toBe(true);

  const items = body.data?.items ?? [];
  expect(items.length, 'At least one item must be returned for anti-leakage check').toBeGreaterThan(0);

  for (const item of items) {
    // Snake-case and camel-case variants — neither must appear
    expect(item, `Item must not expose 'catalogVisibilityPolicyMode'`).not.toHaveProperty(
      'catalogVisibilityPolicyMode',
    );
    expect(item, `Item must not expose 'catalog_visibility_policy_mode'`).not.toHaveProperty(
      'catalog_visibility_policy_mode',
    );
    expect(item, `Item must not expose 'publicationPosture'`).not.toHaveProperty(
      'publicationPosture',
    );
    expect(item, `Item must not expose 'publication_posture'`).not.toHaveProperty(
      'publication_posture',
    );
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// E2E-11: Supplier (qa-b2b owner) sees own catalog including HIDDEN + APPROVED_BUYER_ONLY
// ─────────────────────────────────────────────────────────────────────────────
test('E2E-11: Supplier (qa-b2b owner) sees all own catalog items including HIDDEN and APPROVED_BUYER_ONLY', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: QA credential env vars not set');

  // Supplier's own catalog management view (RLS-scoped to their tenantId)
  const res: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/items?limit=100`,
    { headers: authHeaders(tokenS) },
  );
  expect(res.ok(), `Expected 200, got HTTP ${res.status()}`).toBe(true);

  const body = await res.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  expect(body.success).toBe(true);

  const items = body.data?.items ?? [];
  const skus = items.map((i) => i.sku);

  // Supplier must see ALL their own items — RLS gives them full visibility over their own data
  expect(skus, 'Supplier must see FAB-004 (APPROVED_BUYER_ONLY) in own catalog').toContain(
    'QA-B2B-FAB-004',
  );
  expect(skus, 'Supplier must see FAB-005 (APPROVED_BUYER_ONLY) in own catalog').toContain(
    'QA-B2B-FAB-005',
  );
  expect(skus, 'Supplier must see FAB-006 (HIDDEN) in own catalog').toContain('QA-B2B-FAB-006');

  // Capture FAB-006 UUID as a side-effect (also resolved in beforeAll from supplier catalog)
  const fab006 = items.find((i) => i.sku === 'QA-B2B-FAB-006');
  if (fab006 && !fab006ItemId) {
    fab006ItemId = fab006.id;
  }
});
