/**
 * TECS-SUPPLIER-CATALOG-APPROVAL-GATE-QA-001
 * Runtime Approval-Gate Playwright Verification
 *
 * Tests: AG-01 through AG-12
 * Target: https://app.texqtic.com (controlled via PLAYWRIGHT_BASE_URL env var)
 *
 * Run:
 *   npx playwright test tests/e2e/supplier-catalog-approval-gate.spec.ts
 *
 * Mode: READ-ONLY — no persistent data mutation.
 *       AG-08 creates RFQ drafts but the gate denies them before creation (ok: false).
 *
 * All tests skip automatically (BLOCKED_BY_AUTH) if no QA credentials are available.
 *
 * QA data contract (seeded by Slice F/G — bfb3f64, 493f684):
 *
 *   qa-b2b supplier items:
 *     QA-B2B-FAB-003  B2B_PUBLIC + RELATIONSHIP_ONLY pdpm   (PUBLIC visibility; gated price)
 *     QA-B2B-FAB-004  B2B_PUBLIC + APPROVED_BUYER_ONLY cvpm (visible only to APPROVED buyer)
 *     QA-B2B-FAB-005  B2B_PUBLIC + APPROVED_BUYER_ONLY cvpm + RELATIONSHIP_ONLY pdpm
 *     QA-B2B-FAB-006  PRIVATE_OR_AUTH_ONLY + HIDDEN cvpm    (visible to no buyer)
 *
 *   qa-knt-b supplier items (buildSupplierCatalogItems):
 *     QA-KNT-B-FAB-003  B2B_PUBLIC + APPROVED_BUYER_ONLY cvpm
 *     QA-KNT-B-FAB-004  B2B_PUBLIC + APPROVED_BUYER_ONLY cvpm
 *
 *   Relationships:
 *     Buyer A (qa-buyer-a)  ↔ qa-b2b:  APPROVED
 *     Buyer B (qa-buyer)    ↔ qa-b2b:  REQUESTED
 *     Buyer C (qa-buyer-c)  ↔ qa-b2b:  NONE
 *     Buyer A (qa-buyer-a)  ↔ qa-knt-b: APPROVED
 *     Buyer B (qa-buyer)    ↔ qa-knt-b: REJECTED
 *     Buyer C (qa-buyer-c)  ↔ qa-knt-b: NONE
 *     qa-b2b supplier token ↔ qa-knt-b: NONE (no buyer relationship)
 *
 * Predecessor commits:
 *   f84a662  governance(catalog): close TECS-CATALOG-VISIBILITY-POLICY-STORAGE-001
 *   493f684  test(e2e): add visibility policy gating E2E scenarios (Slice G)
 *   bfb3f64  qa(seed): restore visibility policy intent via catalog_visibility_policy_mode
 */

// Note: @playwright/test is an npx / QA-only dependency — not a project devDependency.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error @playwright/test resolved via npx at test run time
import { test, expect } from '@playwright/test';
// @ts-expect-error @playwright/test resolved via npx at test run time
import type { APIRequestContext, APIResponse } from '@playwright/test';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

// ─── Base URL ────────────────────────────────────────────────────────────────
const BASE_URL = (process.env.PLAYWRIGHT_BASE_URL ?? 'https://app.texqtic.com').replace(/\/$/, '');

// ─── QA identity constants (emails are deterministic from seed) ──────────────
const QA_BUYER_A_EMAIL = 'qa.buyer.wvg.a@texqtic.com';
const QA_BUYER_B_EMAIL = 'qa.buyer@texqtic.com';
const QA_BUYER_C_EMAIL = 'qa.buyer.knt.c@texqtic.com';
const QA_B2B_EMAIL     = 'qa.b2b@texqtic.com';

// ─── Method A: file-based auth state (.auth/*.json — gitignored) ─────────────
// Generated by: pnpm exec tsx tests/e2e/setup-auth-state.ts
// Preferred over env vars — no passwords ever stored or passed to this process.
interface StoredAuthState { token: string; orgId: string; }

function loadStoredAuth(name: string): StoredAuthState | null {
  try {
    const file = join(process.cwd(), '.auth', `${name}.json`);
    if (!existsSync(file)) return null;
    const parsed = JSON.parse(readFileSync(file, 'utf8')) as unknown;
    const s = parsed as StoredAuthState;
    if (typeof s.token === 'string' && s.token.length > 0 &&
        typeof s.orgId === 'string' && s.orgId.length > 0) {
      return s;
    }
    return null;
  } catch { return null; }
}

const storedA = loadStoredAuth('qa-buyer-a');
const storedB = loadStoredAuth('qa-buyer-b');
const storedC = loadStoredAuth('qa-buyer-c');
const storedS = loadStoredAuth('qa-b2b');
const FILE_AUTH_AVAILABLE =
  storedA !== null && storedB !== null && storedC !== null && storedS !== null;

// ─── Method B: env-var credentials (fallback) ────────────────────────────────
const QA_BUYER_A_ORG_ID   = process.env.QA_BUYER_A_ORG_ID   ?? '';
const QA_BUYER_A_PASSWORD = process.env.QA_BUYER_A_PASSWORD ?? '';
const QA_BUYER_B_ORG_ID   = process.env.QA_BUYER_B_ORG_ID   ?? '';
const QA_BUYER_B_PASSWORD = process.env.QA_BUYER_B_PASSWORD ?? '';
const QA_BUYER_C_ORG_ID   = process.env.QA_BUYER_C_ORG_ID   ?? '';
const QA_BUYER_C_PASSWORD = process.env.QA_BUYER_C_PASSWORD ?? '';
const QA_B2B_ORG_ID       = process.env.QA_B2B_ORG_ID       ?? '';
const QA_B2B_PASSWORD     = process.env.QA_B2B_PASSWORD     ?? '';
const ENV_AUTH_AVAILABLE =
  QA_BUYER_A_ORG_ID.length > 0 && QA_BUYER_A_PASSWORD.length > 0 &&
  QA_BUYER_B_ORG_ID.length > 0 && QA_BUYER_B_PASSWORD.length > 0 &&
  QA_BUYER_C_ORG_ID.length > 0 && QA_BUYER_C_PASSWORD.length > 0 &&
  QA_B2B_ORG_ID.length > 0     && QA_B2B_PASSWORD.length > 0;

// ─── Auth availability (Method A preferred, Method B fallback) ───────────────
const CREDENTIALS_AVAILABLE = FILE_AUTH_AVAILABLE || ENV_AUTH_AVAILABLE;
const AUTH_METHOD: 'file' | 'env' | 'none' =
  FILE_AUTH_AVAILABLE ? 'file' : ENV_AUTH_AVAILABLE ? 'env' : 'none';

// ─── Session-scoped JWT tokens (populated in beforeAll) ───────────────────────
let tokenA = '';  // Buyer A  — APPROVED with qa-b2b AND qa-knt-b
let tokenB = '';  // Buyer B  — REQUESTED with qa-b2b, REJECTED with qa-knt-b
let tokenC = '';  // Buyer C  — NONE with all suppliers
let tokenS = '';  // Supplier qa-b2b — item owner; NONE with qa-knt-b as buyer

// ─── Resolved runtime IDs (populated in beforeAll) ───────────────────────────
let supplierOrgId     = '';  // qa-b2b org UUID
let kntBSupplierOrgId = '';  // qa-knt-b org UUID
let fab003ItemId      = '';  // QA-B2B-FAB-003: PUBLIC + RELATIONSHIP_ONLY price
let fab004ItemId      = '';  // QA-B2B-FAB-004: PUBLIC + APPROVED_BUYER_ONLY
let fab005ItemId      = '';  // QA-B2B-FAB-005: PUBLIC + APPROVED_BUYER_ONLY + RELATIONSHIP_ONLY price
let fab006ItemId      = '';  // QA-B2B-FAB-006: PRIVATE_OR_AUTH_ONLY + HIDDEN
let kntBFab003ItemId  = '';  // QA-KNT-B-FAB-003: PUBLIC + APPROVED_BUYER_ONLY (knt-b)
let kntBFab004ItemId  = '';  // QA-KNT-B-FAB-004: PUBLIC + APPROVED_BUYER_ONLY (knt-b)

// ─── Helper: login and return JWT ─────────────────────────────────────────────
async function loginQA(
  request: APIRequestContext,
  email: string,
  password: string,
  tenantId: string,
): Promise<string> {
  const res: APIResponse = await request.post(`${BASE_URL}/api/auth/tenant/login`, {
    headers: { 'Content-Type': 'application/json' },
    data: { email, password, tenantId },
  });
  const body = await res.json() as { success: boolean; data?: { token?: string } };
  if (!res.ok() || !body.success || typeof body.data?.token !== 'string') {
    throw new Error(
      `QA login failed for ${email}: HTTP ${res.status()} success=${body.success}`,
    );
  }
  return body.data.token;
}

// ─── Helper: auth headers ─────────────────────────────────────────────────────
function authHeaders(token: string): Record<string, string> {
  return {
    Authorization: `Bearer ${token}`,
    'Content-Type': 'application/json',
  };
}

// ─── beforeAll: load tokens, resolve supplier org IDs and item UUIDs ──────────
test.beforeAll(async ({ request }: { request: APIRequestContext }) => {
  if (!CREDENTIALS_AVAILABLE) return;

  if (AUTH_METHOD === 'file') {
    // Method A: pre-captured tokens from .auth/*.json — no login calls needed
    tokenA = storedA!.token;
    tokenB = storedB!.token;
    tokenC = storedC!.token;
    tokenS = storedS!.token;
    supplierOrgId = storedS!.orgId;  // qa-b2b's orgId is stored in .auth/qa-b2b.json
  } else {
    // Method B: authenticate via API using env var credentials
    [tokenA, tokenB, tokenC, tokenS] = await Promise.all([
      loginQA(request, QA_BUYER_A_EMAIL, QA_BUYER_A_PASSWORD, QA_BUYER_A_ORG_ID),
      loginQA(request, QA_BUYER_B_EMAIL, QA_BUYER_B_PASSWORD, QA_BUYER_B_ORG_ID),
      loginQA(request, QA_BUYER_C_EMAIL, QA_BUYER_C_PASSWORD, QA_BUYER_C_ORG_ID),
      loginQA(request, QA_B2B_EMAIL,     QA_B2B_PASSWORD,     QA_B2B_ORG_ID),
    ]);
    supplierOrgId = QA_B2B_ORG_ID;
  }

  // Resolve both qa-b2b (if not set) and qa-knt-b org UUIDs from eligible-suppliers
  const suppliersRes: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/b2b/eligible-suppliers`,
    { headers: authHeaders(tokenA) },
  );
  const suppliersBody = await suppliersRes.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; slug: string }>; total: number };
  };
  if (suppliersRes.ok() && suppliersBody.success) {
    const suppliers = suppliersBody.data?.items ?? [];
    if (!supplierOrgId) {
      supplierOrgId = suppliers.find((s) => s.slug === 'qa-b2b')?.id ?? '';
    }
    kntBSupplierOrgId = suppliers.find((s) => s.slug === 'qa-knt-b')?.id ?? '';
  }

  // Resolve qa-b2b item UUIDs from Buyer A browse (APPROVED → sees all non-HIDDEN items)
  if (supplierOrgId) {
    const buyerABrowseRes: APIResponse = await request.get(
      `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
      { headers: authHeaders(tokenA) },
    );
    const browseBody = await buyerABrowseRes.json() as {
      success: boolean;
      data?: { items: Array<{ id: string; sku: string | null }> };
    };
    if (buyerABrowseRes.ok() && browseBody.success) {
      const items = browseBody.data?.items ?? [];
      fab003ItemId = items.find((i) => i.sku === 'QA-B2B-FAB-003')?.id ?? '';
      fab004ItemId = items.find((i) => i.sku === 'QA-B2B-FAB-004')?.id ?? '';
      fab005ItemId = items.find((i) => i.sku === 'QA-B2B-FAB-005')?.id ?? '';
    }
  }

  // Resolve FAB-006 UUID from supplier's own catalog management view
  // (FAB-006 is HIDDEN — it never appears in any buyer browse response)
  const supplierCatalogRes: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/items?limit=100`,
    { headers: authHeaders(tokenS) },
  );
  const supplierCatalogBody = await supplierCatalogRes.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  if (supplierCatalogRes.ok() && supplierCatalogBody.success) {
    fab006ItemId =
      (supplierCatalogBody.data?.items ?? []).find((i) => i.sku === 'QA-B2B-FAB-006')?.id ?? '';
  }

  // Resolve qa-knt-b APPROVED_BUYER_ONLY item UUIDs via Buyer A browse
  // (Buyer A IS APPROVED with qa-knt-b → sees their APPROVED_BUYER_ONLY items)
  if (kntBSupplierOrgId) {
    const kntBBrowseRes: APIResponse = await request.get(
      `${BASE_URL}/api/tenant/catalog/supplier/${kntBSupplierOrgId}/items?limit=100`,
      { headers: authHeaders(tokenA) },
    );
    const kntBBrowseBody = await kntBBrowseRes.json() as {
      success: boolean;
      data?: { items: Array<{ id: string; sku: string | null }> };
    };
    if (kntBBrowseRes.ok() && kntBBrowseBody.success) {
      const kntBItems = kntBBrowseBody.data?.items ?? [];
      kntBFab003ItemId = kntBItems.find((i) => i.sku === 'QA-KNT-B-FAB-003')?.id ?? '';
      kntBFab004ItemId = kntBItems.find((i) => i.sku === 'QA-KNT-B-FAB-004')?.id ?? '';
    }
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// AG-01: Buyer A (APPROVED) browse includes APPROVED_BUYER_ONLY items
// ─────────────────────────────────────────────────────────────────────────────
test('AG-01: Buyer A (APPROVED) browse includes APPROVED_BUYER_ONLY items from qa-b2b', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: no QA credentials available');

  const res: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
    { headers: authHeaders(tokenA) },
  );
  expect(res.ok(), `AG-01: Expected 200, got HTTP ${res.status()}`).toBe(true);

  const body = await res.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  expect(body.success, 'AG-01: Response envelope must be success=true').toBe(true);

  const skus = (body.data?.items ?? []).map((i) => i.sku);

  // APPROVED buyer must see APPROVED_BUYER_ONLY items
  expect(
    skus,
    'AG-01: FAB-004 (APPROVED_BUYER_ONLY) must be visible to APPROVED Buyer A',
  ).toContain('QA-B2B-FAB-004');
  expect(
    skus,
    'AG-01: FAB-005 (APPROVED_BUYER_ONLY) must be visible to APPROVED Buyer A',
  ).toContain('QA-B2B-FAB-005');
  // HIDDEN item must NEVER appear regardless of relationship
  expect(
    skus,
    'AG-01: FAB-006 (HIDDEN) must not appear even for APPROVED buyer',
  ).not.toContain('QA-B2B-FAB-006');
});

// ─────────────────────────────────────────────────────────────────────────────
// AG-02: Buyer B (REQUESTED) browse excludes APPROVED_BUYER_ONLY items
// ─────────────────────────────────────────────────────────────────────────────
test('AG-02: Buyer B (REQUESTED) browse excludes APPROVED_BUYER_ONLY items from qa-b2b', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: no QA credentials available');

  const res: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
    { headers: authHeaders(tokenB) },
  );
  expect(res.ok(), `AG-02: Expected 200, got HTTP ${res.status()}`).toBe(true);

  const body = await res.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  expect(body.success, 'AG-02: Response envelope must be success=true').toBe(true);

  const skus = (body.data?.items ?? []).map((i) => i.sku);

  expect(
    skus,
    'AG-02: FAB-004 (APPROVED_BUYER_ONLY) must be absent for REQUESTED buyer',
  ).not.toContain('QA-B2B-FAB-004');
  expect(
    skus,
    'AG-02: FAB-005 (APPROVED_BUYER_ONLY) must be absent for REQUESTED buyer',
  ).not.toContain('QA-B2B-FAB-005');
  expect(
    skus,
    'AG-02: FAB-006 (HIDDEN) must not appear for any buyer',
  ).not.toContain('QA-B2B-FAB-006');
});

// ─────────────────────────────────────────────────────────────────────────────
// AG-03: Buyer C (no relationship) browse excludes APPROVED_BUYER_ONLY items
// ─────────────────────────────────────────────────────────────────────────────
test('AG-03: Buyer C (no relationship) browse excludes APPROVED_BUYER_ONLY items from qa-b2b', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: no QA credentials available');

  const res: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
    { headers: authHeaders(tokenC) },
  );
  expect(res.ok(), `AG-03: Expected 200, got HTTP ${res.status()}`).toBe(true);

  const body = await res.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  expect(body.success, 'AG-03: Response envelope must be success=true').toBe(true);

  const skus = (body.data?.items ?? []).map((i) => i.sku);

  expect(
    skus,
    'AG-03: FAB-004 (APPROVED_BUYER_ONLY) must be absent for buyer with no relationship',
  ).not.toContain('QA-B2B-FAB-004');
  expect(
    skus,
    'AG-03: FAB-005 (APPROVED_BUYER_ONLY) must be absent for buyer with no relationship',
  ).not.toContain('QA-B2B-FAB-005');
  expect(
    skus,
    'AG-03: FAB-006 (HIDDEN) must not appear for any buyer',
  ).not.toContain('QA-B2B-FAB-006');
});

// ─────────────────────────────────────────────────────────────────────────────
// AG-04: Cross-supplier isolation — each supplier's approval gate is independent
//
// Verifies that catalog approval is scoped to each specific supplier:
//   (a) Buyer A (APPROVED with qa-knt-b) CAN see qa-knt-b APPROVED_BUYER_ONLY items
//   (b) Buyer B (REJECTED with qa-knt-b) CANNOT see qa-knt-b APPROVED_BUYER_ONLY items
//   (c) Buyer C (NONE with qa-knt-b)     CANNOT see qa-knt-b APPROVED_BUYER_ONLY items
//
// Combined with AG-01: Buyer B's REQUESTED state with qa-b2b does not elevate to
// any approval at qa-knt-b, and per-supplier gating is enforced independently.
// ─────────────────────────────────────────────────────────────────────────────
test('AG-04: Cross-supplier isolation — qa-knt-b approval gate is independent of qa-b2b', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: no QA credentials available');
  test.skip(
    !kntBSupplierOrgId,
    'BLOCKED_BY_DATA: qa-knt-b org UUID not resolved — verify qa-knt-b is PUBLICATION_ELIGIBLE',
  );

  // (a) Buyer A (APPROVED with qa-knt-b) sees qa-knt-b APPROVED_BUYER_ONLY items
  const resA: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${kntBSupplierOrgId}/items?limit=100`,
    { headers: authHeaders(tokenA) },
  );
  expect(resA.ok(), `AG-04a: Expected 200 for Buyer A on qa-knt-b, got ${resA.status()}`).toBe(true);

  const bodyA = await resA.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  expect(bodyA.success, 'AG-04a: Buyer A qa-knt-b browse must be success=true').toBe(true);
  const skusA = (bodyA.data?.items ?? []).map((i) => i.sku);

  expect(
    skusA,
    'AG-04a: QA-KNT-B-FAB-003 (APPROVED_BUYER_ONLY) must be visible to Buyer A (APPROVED with qa-knt-b)',
  ).toContain('QA-KNT-B-FAB-003');
  expect(
    skusA,
    'AG-04a: QA-KNT-B-FAB-004 (APPROVED_BUYER_ONLY) must be visible to Buyer A (APPROVED with qa-knt-b)',
  ).toContain('QA-KNT-B-FAB-004');

  // (b) Buyer B (REJECTED with qa-knt-b) cannot see qa-knt-b APPROVED_BUYER_ONLY items
  const resB: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${kntBSupplierOrgId}/items?limit=100`,
    { headers: authHeaders(tokenB) },
  );
  expect(resB.ok(), `AG-04b: Expected 200 for Buyer B on qa-knt-b, got ${resB.status()}`).toBe(true);

  const bodyB = await resB.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  expect(bodyB.success, 'AG-04b: Buyer B qa-knt-b browse must be success=true').toBe(true);
  const skusB = (bodyB.data?.items ?? []).map((i) => i.sku);

  expect(
    skusB,
    'AG-04b: QA-KNT-B-FAB-003 must be absent for Buyer B (REJECTED with qa-knt-b)',
  ).not.toContain('QA-KNT-B-FAB-003');
  expect(
    skusB,
    'AG-04b: QA-KNT-B-FAB-004 must be absent for Buyer B (REJECTED with qa-knt-b)',
  ).not.toContain('QA-KNT-B-FAB-004');

  // (c) Buyer C (NONE with qa-knt-b) cannot see qa-knt-b APPROVED_BUYER_ONLY items
  const resC: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${kntBSupplierOrgId}/items?limit=100`,
    { headers: authHeaders(tokenC) },
  );
  expect(resC.ok(), `AG-04c: Expected 200 for Buyer C on qa-knt-b, got ${resC.status()}`).toBe(true);

  const bodyC = await resC.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  expect(bodyC.success, 'AG-04c: Buyer C qa-knt-b browse must be success=true').toBe(true);
  const skusC = (bodyC.data?.items ?? []).map((i) => i.sku);

  expect(
    skusC,
    'AG-04c: QA-KNT-B-FAB-003 must be absent for Buyer C (NONE with qa-knt-b)',
  ).not.toContain('QA-KNT-B-FAB-003');
  expect(
    skusC,
    'AG-04c: QA-KNT-B-FAB-004 must be absent for Buyer C (NONE with qa-knt-b)',
  ).not.toContain('QA-KNT-B-FAB-004');
});

// ─────────────────────────────────────────────────────────────────────────────
// AG-05: HIDDEN item (FAB-006) PDP returns 404 for APPROVED buyer — non-disclosing
// ─────────────────────────────────────────────────────────────────────────────
test('AG-05: HIDDEN item (FAB-006) PDP returns 404 for APPROVED buyer (Buyer A)', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: no QA credentials available');
  test.skip(
    !fab006ItemId,
    'BLOCKED_BY_DATA: FAB-006 UUID not resolved — verify QA-B2B-FAB-006 is seeded and QA_B2B_PASSWORD is set',
  );

  const res: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/items/${fab006ItemId}`,
    { headers: authHeaders(tokenA) },
  );
  expect(
    res.status(),
    'AG-05: HIDDEN item PDP must return 404 for APPROVED buyer (non-disclosing gate)',
  ).toBe(404);
});

// ─────────────────────────────────────────────────────────────────────────────
// AG-06: HIDDEN item (FAB-006) PDP returns 404 for REQUESTED and no-relationship buyers
// ─────────────────────────────────────────────────────────────────────────────
test('AG-06: HIDDEN item (FAB-006) PDP returns 404 for Buyer B (REQUESTED) and Buyer C (NONE)', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: no QA credentials available');
  test.skip(
    !fab006ItemId,
    'BLOCKED_BY_DATA: FAB-006 UUID not resolved — verify QA-B2B-FAB-006 is seeded and QA_B2B_PASSWORD is set',
  );

  const [resB, resC]: APIResponse[] = await Promise.all([
    request.get(
      `${BASE_URL}/api/tenant/catalog/items/${fab006ItemId}`,
      { headers: authHeaders(tokenB) },
    ),
    request.get(
      `${BASE_URL}/api/tenant/catalog/items/${fab006ItemId}`,
      { headers: authHeaders(tokenC) },
    ),
  ]);

  expect(
    resB.status(),
    'AG-06: HIDDEN item PDP must return 404 for REQUESTED buyer (non-disclosing gate)',
  ).toBe(404);
  expect(
    resC.status(),
    'AG-06: HIDDEN item PDP must return 404 for NONE buyer (non-disclosing gate)',
  ).toBe(404);
});

// ─────────────────────────────────────────────────────────────────────────────
// AG-07: Relationship-only price visible only to approved buyer (FAB-003 PDP)
//
// FAB-003 is B2B_PUBLIC (visible to all authenticated buyers via browse and PDP)
// but its priceDisclosurePolicyMode=RELATIONSHIP_ONLY means price disclosure state
// differs by buyer relationship:
//   APPROVED buyer (Buyer A)  → priceDisclosure.price_visibility_state is a positive state
//   REQUESTED buyer (Buyer B) → priceDisclosure.price_visibility_state === 'ELIGIBILITY_REQUIRED'
//   NONE buyer (Buyer C)      → priceDisclosure.price_visibility_state === 'ELIGIBILITY_REQUIRED'
//
// Anti-leakage: PDP response must not expose priceDisclosurePolicyMode or publicationPosture.
// ─────────────────────────────────────────────────────────────────────────────
test('AG-07: Relationship-only price visible only to approved buyer (FAB-003 PDP priceDisclosure)', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: no QA credentials available');
  test.skip(
    !fab003ItemId,
    'BLOCKED_BY_DATA: FAB-003 UUID not resolved — item may be missing from qa-b2b catalog',
  );

  // All three buyers can access FAB-003 PDP (PUBLIC visibility) — price disclosure differs
  const [resA, resB, resC]: APIResponse[] = await Promise.all([
    request.get(
      `${BASE_URL}/api/tenant/catalog/items/${fab003ItemId}`,
      { headers: authHeaders(tokenA) },
    ),
    request.get(
      `${BASE_URL}/api/tenant/catalog/items/${fab003ItemId}`,
      { headers: authHeaders(tokenB) },
    ),
    request.get(
      `${BASE_URL}/api/tenant/catalog/items/${fab003ItemId}`,
      { headers: authHeaders(tokenC) },
    ),
  ]);

  // All must return 200 — FAB-003 has null cvpm (PUBLIC visibility), accessible to all auth'd buyers
  expect(resA.status(), 'AG-07: FAB-003 PDP must return 200 for Buyer A (APPROVED)').toBe(200);
  expect(
    resB.status(),
    'AG-07: FAB-003 PDP must return 200 for Buyer B (REQUESTED — PUBLIC visibility)',
  ).toBe(200);
  expect(
    resC.status(),
    'AG-07: FAB-003 PDP must return 200 for Buyer C (NONE — PUBLIC visibility)',
  ).toBe(200);

  type PdpResponse = {
    success: boolean;
    data?: {
      itemId?: string;
      priceDisclosure?: {
        price_visibility_state?: string;
        price_value_visible?: boolean;
      };
      // The following must NOT be present in any buyer-facing PDP response:
      priceDisclosurePolicyMode?: unknown;
      price_disclosure_policy_mode?: unknown;
      catalogVisibilityPolicyMode?: unknown;
      catalog_visibility_policy_mode?: unknown;
      publicationPosture?: unknown;
      publication_posture?: unknown;
    };
  };

  const bodyA = await resA.json() as PdpResponse;
  const bodyB = await resB.json() as PdpResponse;
  const bodyC = await resC.json() as PdpResponse;

  expect(bodyA.success, 'AG-07: Buyer A PDP response must be success=true').toBe(true);
  expect(bodyB.success, 'AG-07: Buyer B PDP response must be success=true').toBe(true);
  expect(bodyC.success, 'AG-07: Buyer C PDP response must be success=true').toBe(true);

  // Buyer A (APPROVED): price disclosure must be a positive eligibility state (not denied)
  const DENIED_PRICE_STATES = ['ELIGIBILITY_REQUIRED', 'HIDDEN', 'LOGIN_REQUIRED'];
  const stateA = bodyA.data?.priceDisclosure?.price_visibility_state;
  expect(stateA, 'AG-07: priceDisclosure must be present in Buyer A PDP response').toBeTruthy();
  expect(
    DENIED_PRICE_STATES,
    `AG-07: APPROVED Buyer A must not receive a denied price state; got '${stateA}'`,
  ).not.toContain(stateA);

  // Buyer B (REQUESTED): price disclosure is ELIGIBILITY_REQUIRED (RELATIONSHIP_ONLY policy)
  expect(
    bodyB.data?.priceDisclosure?.price_visibility_state,
    'AG-07: REQUESTED Buyer B must receive ELIGIBILITY_REQUIRED price state (RELATIONSHIP_ONLY policy)',
  ).toBe('ELIGIBILITY_REQUIRED');

  // Buyer C (NONE): price disclosure is ELIGIBILITY_REQUIRED (RELATIONSHIP_ONLY policy)
  expect(
    bodyC.data?.priceDisclosure?.price_visibility_state,
    'AG-07: NONE Buyer C must receive ELIGIBILITY_REQUIRED price state (RELATIONSHIP_ONLY policy)',
  ).toBe('ELIGIBILITY_REQUIRED');

  // Anti-leakage: internal policy fields must NOT be present in PDP response for any buyer
  for (const [label, body] of [
    ['Buyer A', bodyA],
    ['Buyer B', bodyB],
    ['Buyer C', bodyC],
  ] as [string, PdpResponse][]) {
    expect(
      body.data,
      `AG-07: PDP for ${label} must not expose priceDisclosurePolicyMode`,
    ).not.toHaveProperty('priceDisclosurePolicyMode');
    expect(
      body.data,
      `AG-07: PDP for ${label} must not expose price_disclosure_policy_mode`,
    ).not.toHaveProperty('price_disclosure_policy_mode');
    expect(
      body.data,
      `AG-07: PDP for ${label} must not expose catalogVisibilityPolicyMode`,
    ).not.toHaveProperty('catalogVisibilityPolicyMode');
    expect(
      body.data,
      `AG-07: PDP for ${label} must not expose catalog_visibility_policy_mode`,
    ).not.toHaveProperty('catalog_visibility_policy_mode');
    expect(
      body.data,
      `AG-07: PDP for ${label} must not expose publicationPosture`,
    ).not.toHaveProperty('publicationPosture');
    expect(
      body.data,
      `AG-07: PDP for ${label} must not expose publication_posture`,
    ).not.toHaveProperty('publication_posture');
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// AG-08: RFQ gate denies unapproved buyers on APPROVED_BUYER_ONLY item (FAB-004)
// ─────────────────────────────────────────────────────────────────────────────
test('AG-08: RFQ gate returns ok=false for Buyer B (REQUESTED) and Buyer C (NONE) on FAB-004', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: no QA credentials available');
  test.skip(
    !fab004ItemId,
    'BLOCKED_BY_DATA: FAB-004 UUID not resolved — check qa-b2b catalog has QA-B2B-FAB-004',
  );

  const [resB, resC]: APIResponse[] = await Promise.all([
    request.post(`${BASE_URL}/api/tenant/rfqs/drafts/from-catalog-item`, {
      headers: authHeaders(tokenB),
      data: { catalogItemId: fab004ItemId, selectedQuantity: 100 },
    }),
    request.post(`${BASE_URL}/api/tenant/rfqs/drafts/from-catalog-item`, {
      headers: authHeaders(tokenC),
      data: { catalogItemId: fab004ItemId, selectedQuantity: 100 },
    }),
  ]);

  // Envelope is HTTP 200 with ok: false (not 201 — 201 is success-with-draft creation only)
  expect(resB.ok(), `AG-08: Buyer B RFQ prefill must return HTTP 2xx envelope`).toBe(true);
  expect(resC.ok(), `AG-08: Buyer C RFQ prefill must return HTTP 2xx envelope`).toBe(true);

  type RfqPrefillResponse = {
    success: boolean;
    data?: { ok: boolean; reason?: string };
  };
  const bodyB = await resB.json() as RfqPrefillResponse;
  const bodyC = await resC.json() as RfqPrefillResponse;

  expect(bodyB.success, 'AG-08: Buyer B RFQ prefill envelope must be success=true').toBe(true);
  expect(bodyC.success, 'AG-08: Buyer C RFQ prefill envelope must be success=true').toBe(true);

  const GATE_REASONS = ['ITEM_NOT_AVAILABLE', 'ELIGIBILITY_REQUIRED'];

  expect(
    bodyB.data?.ok,
    'AG-08: RFQ prefill must return ok=false for REQUESTED buyer on APPROVED_BUYER_ONLY item',
  ).toBe(false);
  expect(
    GATE_REASONS,
    `AG-08: RFQ gate reason for Buyer B must be ITEM_NOT_AVAILABLE or ELIGIBILITY_REQUIRED; got '${bodyB.data?.reason}'`,
  ).toContain(bodyB.data?.reason);

  expect(
    bodyC.data?.ok,
    'AG-08: RFQ prefill must return ok=false for NONE buyer on APPROVED_BUYER_ONLY item',
  ).toBe(false);
  expect(
    GATE_REASONS,
    `AG-08: RFQ gate reason for Buyer C must be ITEM_NOT_AVAILABLE or ELIGIBILITY_REQUIRED; got '${bodyC.data?.reason}'`,
  ).toContain(bodyC.data?.reason);
});

// ─────────────────────────────────────────────────────────────────────────────
// AG-09: Direct PDP URL is non-disclosing for denied access
//
// Denied buyers (Buyer B and Buyer C) on FAB-004 (APPROVED_BUYER_ONLY):
//   → receive HTTP 404 (not 403 — non-disclosing gate design)
//   → 404 response body MUST NOT reveal: item UUID, item SKU, or policy field names
// ─────────────────────────────────────────────────────────────────────────────
test('AG-09: PDP URL is non-disclosing — FAB-004 returns 404 with no item data for denied buyers', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: no QA credentials available');
  test.skip(
    !fab004ItemId,
    'BLOCKED_BY_DATA: FAB-004 UUID not resolved — check qa-b2b catalog',
  );

  const [resB, resC]: APIResponse[] = await Promise.all([
    request.get(
      `${BASE_URL}/api/tenant/catalog/items/${fab004ItemId}`,
      { headers: authHeaders(tokenB) },
    ),
    request.get(
      `${BASE_URL}/api/tenant/catalog/items/${fab004ItemId}`,
      { headers: authHeaders(tokenC) },
    ),
  ]);

  expect(
    resB.status(),
    'AG-09: FAB-004 PDP must return 404 for REQUESTED buyer (non-disclosing gate)',
  ).toBe(404);
  expect(
    resC.status(),
    'AG-09: FAB-004 PDP must return 404 for NONE buyer (non-disclosing gate)',
  ).toBe(404);

  // Anti-leakage: the 404 response body must not reveal item details or internal policy fields
  const rawB = await resB.text();
  const rawC = await resC.text();

  for (const [label, raw] of [
    ['Buyer B', rawB],
    ['Buyer C', rawC],
  ] as [string, string][]) {
    expect(raw, `AG-09: 404 body for ${label} must not contain the item UUID`).not.toContain(
      fab004ItemId,
    );
    expect(raw, `AG-09: 404 body for ${label} must not reveal the item SKU`).not.toContain(
      'QA-B2B-FAB-004',
    );
    expect(
      raw,
      `AG-09: 404 body for ${label} must not expose catalogVisibilityPolicyMode`,
    ).not.toContain('catalogVisibilityPolicyMode');
    expect(
      raw,
      `AG-09: 404 body for ${label} must not expose publicationPosture`,
    ).not.toContain('publicationPosture');
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// AG-10: Browse item count — unapproved buyer sees fewer items than approved buyer
//
// Buyer A (APPROVED) sees FAB-003 + FAB-004 + FAB-005 + other PUBLIC items.
// Buyer C (NONE) sees only PUBLIC items (no FAB-004, no FAB-005, no FAB-006).
// Expected count difference: exactly 2 (FAB-004 + FAB-005).
//
// Additionally: SKU-targeted search for FAB-004 as Buyer C returns 0 results,
// proving the approval gate also applies to filtered/search queries.
// ─────────────────────────────────────────────────────────────────────────────
test('AG-10: Unapproved buyer browse count is smaller than approved buyer by exactly 2 items', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: no QA credentials available');

  const [resA, resC]: APIResponse[] = await Promise.all([
    request.get(
      `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
      { headers: authHeaders(tokenA) },
    ),
    request.get(
      `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
      { headers: authHeaders(tokenC) },
    ),
  ]);

  expect(resA.ok(), `AG-10: Buyer A browse must succeed; got ${resA.status()}`).toBe(true);
  expect(resC.ok(), `AG-10: Buyer C browse must succeed; got ${resC.status()}`).toBe(true);

  type BrowseResponse = {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  const bodyA = await resA.json() as BrowseResponse;
  const bodyC = await resC.json() as BrowseResponse;

  const countA = (bodyA.data?.items ?? []).length;
  const countC = (bodyC.data?.items ?? []).length;

  // Buyer C must see fewer items (APPROVED_BUYER_ONLY items are excluded)
  expect(
    countC,
    `AG-10: Buyer C count (${countC}) must be less than Buyer A count (${countA}) — approval gate reduces visible set`,
  ).toBeLessThan(countA);

  // Difference must be exactly 2: FAB-004 and FAB-005 (only APPROVED_BUYER_ONLY items in qa-b2b seed)
  expect(
    countA - countC,
    `AG-10: Count difference must be exactly 2 (FAB-004 + FAB-005); actual diff was ${countA - countC}`,
  ).toBe(2);

  // SKU-targeted search: Buyer C searches for FAB-004 by SKU prefix → zero results
  const searchRes: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100&q=QA-B2B-FAB-004`,
    { headers: authHeaders(tokenC) },
  );
  expect(searchRes.ok(), `AG-10: Buyer C SKU search must succeed; got ${searchRes.status()}`).toBe(
    true,
  );
  const searchBody = await searchRes.json() as BrowseResponse;
  const searchSkus = (searchBody.data?.items ?? []).map((i) => i.sku);

  expect(
    searchSkus,
    'AG-10: SKU search for QA-B2B-FAB-004 by Buyer C must return 0 results (gate applies to search)',
  ).not.toContain('QA-B2B-FAB-004');
});

// ─────────────────────────────────────────────────────────────────────────────
// AG-11: Client override attempts do not bypass the approval gate
//
// Attempts tested:
//   (a) Browse with extra query params: includeHidden=true, buyerOrgId=fake,
//       catalogVisibilityPolicyMode=PUBLIC, relationshipState=APPROVED
//   (b) Browse with fake override headers: X-Override-Relationship, X-Bypass-Gate
//   (c) PDP for FAB-004 with fake force params — must still return 404
// ─────────────────────────────────────────────────────────────────────────────
test('AG-11: Extra query params and fake headers do not bypass the approval gate for Buyer C', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: no QA credentials available');

  type BrowseResponse = {
    success: boolean;
    data?: { items: Array<{ sku: string | null }> };
  };

  // (a) Browse with override query params — server ignores unknown Zod schema fields
  const overrideParams = new URLSearchParams({
    limit: '100',
    includeHidden: 'true',
    buyerOrgId: '00000000-0000-0000-0000-000000000001',
    catalogVisibilityPolicyMode: 'PUBLIC',
    relationshipState: 'APPROVED',
    forceVisibility: 'ALL',
  }).toString();

  const resOverride: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?${overrideParams}`,
    { headers: authHeaders(tokenC) },
  );
  expect(resOverride.ok(), `AG-11a: Override-param browse must return 2xx envelope`).toBe(true);

  const bodyOverride = await resOverride.json() as BrowseResponse;
  expect(bodyOverride.success, 'AG-11a: Override-param browse envelope must be success=true').toBe(
    true,
  );
  const overrideSkus = (bodyOverride.data?.items ?? []).map((i) => i.sku);

  expect(
    overrideSkus,
    'AG-11a: FAB-004 must remain absent despite includeHidden/buyerOrgId/catalogVisibilityPolicyMode params',
  ).not.toContain('QA-B2B-FAB-004');
  expect(
    overrideSkus,
    'AG-11a: FAB-005 must remain absent despite override query params',
  ).not.toContain('QA-B2B-FAB-005');
  expect(
    overrideSkus,
    'AG-11a: FAB-006 (HIDDEN) must remain absent despite includeHidden=true param',
  ).not.toContain('QA-B2B-FAB-006');

  // (b) Browse with fake relationship override headers
  const resHeader: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${supplierOrgId}/items?limit=100`,
    {
      headers: {
        ...authHeaders(tokenC),
        'X-Override-Relationship': 'APPROVED',
        'X-Bypass-Gate': 'true',
        'X-Catalog-Visibility': 'ALL',
      },
    },
  );
  expect(resHeader.ok(), `AG-11b: Fake-header browse must return 2xx envelope`).toBe(true);

  const bodyHeader = await resHeader.json() as BrowseResponse;
  const headerSkus = (bodyHeader.data?.items ?? []).map((i) => i.sku);

  expect(
    headerSkus,
    'AG-11b: FAB-004 must remain absent despite X-Override-Relationship: APPROVED header',
  ).not.toContain('QA-B2B-FAB-004');
  expect(
    headerSkus,
    'AG-11b: FAB-006 (HIDDEN) must remain absent despite X-Bypass-Gate: true header',
  ).not.toContain('QA-B2B-FAB-006');

  // (c) PDP for FAB-004 with override query params — must still return 404 for Buyer C
  if (fab004ItemId) {
    const resPdpOverride: APIResponse = await request.get(
      `${BASE_URL}/api/tenant/catalog/items/${fab004ItemId}` +
        `?includeHidden=true&force=true&buyerOrgId=00000000-0000-0000-0000-000000000001`,
      { headers: authHeaders(tokenC) },
    );
    expect(
      resPdpOverride.status(),
      'AG-11c: FAB-004 PDP must return 404 for Buyer C even with override query params',
    ).toBe(404);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// AG-12: Dual-role — supplier token (qa-b2b) cannot bypass another supplier's gate
//
// qa-b2b's auth token, when used to browse qa-knt-b catalog as a buyer, has
// no buyer approval relationship with qa-knt-b.
//   → APPROVED_BUYER_ONLY items (QA-KNT-B-FAB-003, FAB-004) must be absent
//   → PUBLIC items from qa-knt-b may still be visible (no gate for those)
//
// Supplier identity check: tokenS can still access its own supplier catalog,
// confirming the token is valid and the gate is not a blanket auth failure.
// ─────────────────────────────────────────────────────────────────────────────
test('AG-12: Supplier token (qa-b2b) cannot access qa-knt-b APPROVED_BUYER_ONLY items as buyer', async ({
  request,
}: { request: APIRequestContext }) => {
  test.skip(!CREDENTIALS_AVAILABLE, 'BLOCKED_BY_AUTH: no QA credentials available');
  test.skip(
    !kntBSupplierOrgId,
    'BLOCKED_BY_DATA: qa-knt-b org UUID not resolved — cannot run dual-role test',
  );

  // Browse qa-knt-b catalog using qa-b2b supplier token (no buyer approval relationship)
  const resSupplierAsBuyer: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/supplier/${kntBSupplierOrgId}/items?limit=100`,
    { headers: authHeaders(tokenS) },
  );
  expect(
    resSupplierAsBuyer.ok(),
    `AG-12: qa-b2b supplier browsing qa-knt-b catalog must return 2xx; got ${resSupplierAsBuyer.status()}`,
  ).toBe(true);

  const body = await resSupplierAsBuyer.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  expect(body.success, 'AG-12: qa-b2b token browse of qa-knt-b must be success=true').toBe(true);

  const skus = (body.data?.items ?? []).map((i) => i.sku);

  // qa-b2b has no buyer approval with qa-knt-b → APPROVED_BUYER_ONLY items must be absent
  expect(
    skus,
    'AG-12: QA-KNT-B-FAB-003 (APPROVED_BUYER_ONLY) must be absent for qa-b2b supplier acting as buyer (no buyer approval with qa-knt-b)',
  ).not.toContain('QA-KNT-B-FAB-003');
  expect(
    skus,
    'AG-12: QA-KNT-B-FAB-004 (APPROVED_BUYER_ONLY) must be absent for qa-b2b supplier acting as buyer (no buyer approval with qa-knt-b)',
  ).not.toContain('QA-KNT-B-FAB-004');

  // Supplier identity check: tokenS can still access its own catalog (no role confusion)
  const resOwnCatalog: APIResponse = await request.get(
    `${BASE_URL}/api/tenant/catalog/items?limit=100`,
    { headers: authHeaders(tokenS) },
  );
  expect(
    resOwnCatalog.ok(),
    `AG-12: qa-b2b supplier must still access own catalog items; got ${resOwnCatalog.status()}`,
  ).toBe(true);

  const ownBody = await resOwnCatalog.json() as {
    success: boolean;
    data?: { items: Array<{ id: string; sku: string | null }> };
  };
  expect(ownBody.success, 'AG-12: qa-b2b own catalog response must be success=true').toBe(true);
  expect(
    (ownBody.data?.items ?? []).length,
    'AG-12: qa-b2b own catalog must return at least 1 item (token is valid; only cross-supplier gate fires)',
  ).toBeGreaterThan(0);
});
