/**
 * vectorIndexQueue.ts — G-028 A6: Async vector indexing queue
 *
 * Task ID: OPS-G028-A6-SOURCE-EXPANSION-ASYNC-INDEXING
 *
 * In-process queue that decouples embedding generation from the request path.
 *
 * Architecture:
 *   entity mutation → enqueueVectorIndexJob() → queue[] → worker tick
 *   worker tick → processVectorIndexQueue(runner) → runner(job)
 *   runner → generateEmbedding() → upsertDocumentEmbeddings()
 *
 * CONSTITUTIONAL CONSTRAINTS:
 *   - Queue is in-process only (no distributed queue, no Redis, no BullMQ)
 *   - Worker lifecycle is tied to the server instance
 *   - No circular imports: runner is injected by caller, not imported here
 *   - All DB writes by the runner MUST run under RLS (withDbContext)
 *   - Raw chunk content MUST NOT be logged (enforced in runner)
 *
 * Performance safeguards (ADR-028 A6 §10):
 *   - QUEUE_SIZE_MAX  = 1000 jobs (rejects ≥ this)
 *   - JOBS_PER_SECOND = 5   (processed per worker tick)
 *   - maxChunks / maxDocSize limits enforced by the runner (vectorIngestion)
 *
 * Known limitations (documented per §14):
 *   - Queue is lost on server restart (no persistence)
 *   - Not suitable for distributed / multi-instance deployments
 *   - Large batch indexing (tenant-wide reindex) may saturate queue
 *
 * @module vectorIndexQueue
 */

import { randomUUID } from 'node:crypto';

// ─── Constants ────────────────────────────────────────────────────────────────

/** Maximum jobs allowed in the queue before new jobs are rejected. */
export const QUEUE_SIZE_MAX = 1_000 as const;

/** Maximum jobs processed per worker tick (1-second interval). */
export const JOBS_PER_SECOND = 5 as const;

/** Worker tick interval in milliseconds. */
const WORKER_INTERVAL_MS = 1_000 as const;

// ─── Types ────────────────────────────────────────────────────────────────────

/**
 * One indexing job in the queue.
 *
 * G-028-B2-DELETE-ENQUEUE-BLOCKER: extended with `operation` discriminator so
 * the queue can carry both upsert (chunk → embed → upsert) and delete
 * (remove all vector chunks for the source) semantics.
 *
 * - operation 'upsert' (or absent): existing ingestion path — requires textContent.
 * - operation 'delete': removes all chunks for (orgId, sourceType, sourceId) — no text needed.
 *
 * `operation` is optional for backwards compatibility: existing callers that omit
 * it are treated as 'upsert'. Use enqueueSourceIngestion() / enqueueSourceDeletion()
 * (in vectorIngestion.ts) rather than enqueueVectorIndexJob() directly.
 */
export interface VectorIndexJob {
  /**
   * Discriminates upsert vs. delete semantics.
   * - 'upsert' (or absent): chunk → embed → upsert (existing ingestion path).
   * - 'delete': remove all vector chunks for (orgId, sourceType, sourceId).
   * Defaults to 'upsert' when absent (backwards-compatible with pre-G028-DELETE callers).
   */
  operation?: 'upsert' | 'delete';
  /** UUID of the tenant org — MUST match req.dbContext.orgId at mutation point. */
  orgId: string;
  /** Domain discriminator (e.g. 'CATALOG_ITEM', 'DPP_SNAPSHOT'). */
  sourceType: string;
  /** UUID of the originating entity. */
  sourceId: string;
  /**
   * Full text to chunk and embed. Required for 'upsert' jobs.
   * Not applicable for 'delete' jobs — omit or leave undefined.
   * Cleared from queue memory after processing.
   */
  textContent?: string;
  /** Optional metadata forwarded to each stored chunk. Upsert-only. */
  metadata?: Record<string, unknown>;
  /** Internal trace ID for observability. Generated by enqueue. */
  readonly _jobId: string;
  /** Enqueue timestamp (ms since epoch). */
  readonly _enqueuedAt: number;
}

/**
 * Function signature for job runners injected into the worker.
 * Implementations MUST use withDbContext to enforce RLS isolation.
 */
export type JobRunner = (job: VectorIndexJob) => Promise<void>;

/** Result of a single processVectorIndexQueue() call. */
export interface ProcessResult {
  attempted: number;
  succeeded: number;
  failed: number;
  remaining: number;
}

/** Result of enqueueVectorIndexJob(). */
export type EnqueueResult =
  | { accepted: true; jobId: string }
  | { accepted: false; reason: 'QUEUE_FULL' };

// ─── Queue state ──────────────────────────────────────────────────────────────

const _queue: VectorIndexJob[] = [];
let _workerHandle: ReturnType<typeof setInterval> | null = null;

// ─── enqueueVectorIndexJob ────────────────────────────────────────────────────

/**
 * Add a job to the async vector indexing queue.
 *
 * - Rejects if queue is at or over QUEUE_SIZE_MAX.
 * - Attaches a trace _jobId and _enqueuedAt timestamp.
 * - Logs queue-full rejections (metadata only, never text content).
 *
 * @returns { accepted: true, jobId } on success, { accepted: false, reason } if full.
 */
export function enqueueVectorIndexJob(
  job: Omit<VectorIndexJob, '_jobId' | '_enqueuedAt'>,
): EnqueueResult {
  if (_queue.length >= QUEUE_SIZE_MAX) {
    console.warn('[G028-A6][vector_queue_full]', {
      stage:      'vector_async_index',
      sourceType: job.sourceType,
      sourceId:   job.sourceId,
      queueSize:  _queue.length,
    });
    return { accepted: false, reason: 'QUEUE_FULL' };
  }

  const jobId = randomUUID();
  const fullJob: VectorIndexJob = {
    ...job,
    _jobId:       jobId,
    _enqueuedAt:  Date.now(),
  };
  _queue.push(fullJob);

  return { accepted: true, jobId };
}

// ─── processVectorIndexQueue ──────────────────────────────────────────────────

/**
 * Process up to JOBS_PER_SECOND jobs from the queue using the provided runner.
 *
 * - Dequeues up to JOBS_PER_SECOND jobs atomically (splice).
 * - Runs each job through the runner; errors are caught per-job (fail-isolated).
 * - Returns counts for observability.
 *
 * IMPORTANT: Callers must ensure the runner sets up RLS context via withDbContext.
 *
 * @param runner Function that indexes one job (embedding + upsert under RLS).
 * @returns ProcessResult with attempt/success/fail counts and remaining queue size.
 */
export async function processVectorIndexQueue(runner: JobRunner): Promise<ProcessResult> {
  const batch = _queue.splice(0, JOBS_PER_SECOND);
  let succeeded = 0;
  let failed = 0;

  for (const job of batch) {
    const start = Date.now();
    try {
      await runner(job);
      succeeded++;
      console.info('[G028-A6][vector_async_index]', {
        stage:      'vector_async_index',
        sourceType: job.sourceType,
        sourceId:   job.sourceId,
        latencyMs:  Date.now() - start,
      });
    } catch (err) {
      failed++;
      console.error('[G028-A6][vector_worker_error]', {
        stage:      'vector_async_index',
        sourceType: job.sourceType,
        sourceId:   job.sourceId,
        jobId:      job._jobId,
        error:      String(err),
      });
      // Continue: one job failure must not block the rest of the queue
    }
  }

  return {
    attempted: batch.length,
    succeeded,
    failed,
    remaining: _queue.length,
  };
}

// ─── startVectorIndexWorker ───────────────────────────────────────────────────

/**
 * Start the background vector indexing worker.
 *
 * Calls processVectorIndexQueue(runner) every WORKER_INTERVAL_MS (1 second),
 * processing up to JOBS_PER_SECOND jobs per tick.
 *
 * - Only one worker is permitted per process (idempotent start).
 * - Returns a `stop()` handle for graceful shutdown.
 * - Worker errors (unexpected) are caught at the interval level.
 *
 * @param runner Function that indexes one job (embedding + upsert under RLS).
 * @returns { stop } — call stop() on server shutdown or in tests.
 */
export function startVectorIndexWorker(runner: JobRunner): { stop: () => void } {
  if (_workerHandle !== null) {
    // Worker already running — return existing stop handle
    return {
      stop: () => {
        if (_workerHandle !== null) {
          clearInterval(_workerHandle);
          _workerHandle = null;
        }
      },
    };
  }

  _workerHandle = setInterval(() => {
    if (_queue.length === 0) return;

    processVectorIndexQueue(runner).catch(err => {
      // Interval-level catch — unexpected error in processVectorIndexQueue itself
      console.error('[G028-A6][worker_interval_error]', { error: String(err) });
    });
  }, WORKER_INTERVAL_MS);

  // Allow Node process to exit even if worker is still running
  if (typeof _workerHandle === 'object' && _workerHandle !== null && 'unref' in _workerHandle) {
    (_workerHandle as ReturnType<typeof setInterval>).unref?.();
  }

  console.info('[G028-A6][worker_started]', {
    stage:            'vector_async_index',
    jobsPerSecond:    JOBS_PER_SECOND,
    queueSizeMax:     QUEUE_SIZE_MAX,
    intervalMs:       WORKER_INTERVAL_MS,
  });

  return {
    stop: () => {
      if (_workerHandle !== null) {
        clearInterval(_workerHandle);
        _workerHandle = null;
        console.info('[G028-A6][worker_stopped]', { stage: 'vector_async_index' });
      }
    },
  };
}

// ─── Test utilities ───────────────────────────────────────────────────────────
// These exports are intended ONLY for vitest tests.
// They are prefixed with _ to signal test-only usage.

/** Return current queue length (test observability). */
export function _getQueueSizeForTests(): number {
  return _queue.length;
}

/** Drain all pending jobs without processing them (test cleanup). */
export function _clearQueueForTests(): void {
  _queue.length = 0;
}

/** Stop the worker if running (call in afterEach to prevent timer leaks). */
export function _stopWorkerForTests(): void {
  if (_workerHandle !== null) {
    clearInterval(_workerHandle);
    _workerHandle = null;
  }
}

/** Peek at the next N jobs without dequeuing (test inspection). */
export function _peekQueueForTests(n = 10): Readonly<VectorIndexJob>[] {
  return _queue.slice(0, n);
}
